export const productsENG = [
  {
    id: 1,
    product: "Centrifuge",
    description: "Leica DM500",
    key:"hsuglw391f",
    manufacturer: "Manufactured: ",
    country: "Germany",
    weight: "Weight: 6 kg",
    price: "97000",
    material: "Steel",
    Product_category: 'Analysis',
    add_to_cart: "Add to cart",
    image: "centrifuge",
    quantity:1,
    Brands: "Flottweg"
  },
  {
    id: 2,
    product: "Spectrophotometer",
    description: "Binder BD56",
    key:"hsa03e01dl",
    manufacturer: "Manufactured: ",
    country: "Germany",
    weight: "Weight: 34 kg",
    price: "125000",
    material: "Aluminum",
    Product_category: 'Research',
    Brands: "Rousselet Robatel",
    image: "spectro",
    quantity:1,
    add_to_cart: "Add to cart"
  },
  {
    id: 3,
    product: "Dividing Centrifuge",
    description: "Shimadzu UV-1900",
    key:"12hlapogb0",
    manufacturer: "Manufactured: ",
    country: "Japan",
    weight: "Weight: 10 kg",
    price: "100000",
    material: "Aluminum",
    Product_category: 'Analysis',
    Brands: "Labor-Microscopes",
    image: "dividing-entrifuge",
    quantity:1,
    add_to_cart: "Add to cart"
  },
  {
    id: 4,
    product: "Nanocrystalline Microscope",
    description: "Z-1000 Nano",
    key:"bdlac3th91",
    manufacturer: "Manufactured: ",
    country: "Sweden",
    weight: "Weight: 8 kg",
    price: "49000",
    material: "Plastic",
    Product_category: 'Research',
    Brands: "Flottweg",
    image: "microscope",
    quantity:1,
    add_to_cart: "Add to cart"
  },
  {
    id: 5,
    product: "Filtration Centrifuge",
    description: "BioGrow BG-3000",
    key:"1fd95nalxu",
    manufacturer: "Manufactured: ",
    country: "USA",
    weight: "Weight: 45 kg",
    price: "50000",
    material: "Steel",
    Product_category: 'Analysis',
    Brands: "Labor-Microscopes",
    image: "Filtration-cytrifuge",
    quantity:1,
    add_to_cart: "Add to cart"
  },
  {
    id: 6,
    product: "Accelerated Centrifuge",
    description: "LaserSpec LS-2000",
    key:"wskibf58sv",
    manufacturer: "Manufactured: ",
    country: "China",
    weight: "Weight: 12 kg",
    price: "40000",
    material: "Carbon Fiber",
    Product_category: 'Research',
    Brands: "Rousselet Robatel",
    image: "centrifuge2",
    quantity:1,
    add_to_cart: "Add to cart"
  },
  {
    id: 7,
    product: "Centrifuge",
    description: "Z-1000Tech",
    key:"bndlage5ns",
    manufacturer: "Manufactured: ",
    country: "Germany",
    weight: "Weight: 6 kg",
    price: "30000",
    material: "Steel",
    Product_category: 'Research',
    Brands: "Rousselet Robatel",
    image: "centrifuge2",
    quantity:1,
    add_to_cart: "Add to cart"
  },
  {
    id: 8,
    product: "Telescope",
    description: "Bind-BD5126",
    key:"bsflthdb83a",
    manufacturer: "Manufactured: ",
    country: "Germany",
    weight: "Weight: 43 kg",
    price: "39000",
    material: "Plastic",
    Product_category: 'Analysis',
    Brands: "Labor-Microscopes",
    image: "telescope",
    quantity:1,
    add_to_cart: "Add to cart"
  },
  {
    id: 9,
    product: "Dividing Centrifuge",
    description: "KandanUV-100",
    key:"sbrg24ba9f",
    manufacturer: "Manufactured: ",
    country: "Japan",
    weight: "Weight: 10 kg",
    price: "57000",
    material: "Carbon Fiber",
    Product_category: 'Research',
    Brands: "Flottweg",
    quantity:1,
    image: "dividing-entrifuge",
    add_to_cart: "Add to cart"
  }
];


 export const productsRUS = [
     {
       id:1,
      product: "Центрифуга",
      description: "Leica DM500",
      key:"hsuglw391f",
      manufacturer: "Произведено: ",
      country: "Германия",
      weight: "Вес: 6 кг",
      price: "97000",
      material:"Сталь",
      Product_category:'Анализ',
      add_to_cart: "Добавить в корзину",
      image:"centrifuge",
      quantity:1,
      Brands:"Flottweg"
    },
    {
      id:2,
      product: "Спектрофотометр",
      description: "Binder BD56",
      key:"hsa03e01dl",
      manufacturer: "Произведено: ",
      country: "Германия",
      weight: "Вес: 34 кг",
      price: "125000",
      material:"Алюминий",
      Product_category:'Исследования',
      Brands:"Rousselet Robatel",
      image:"spectro",
      quantity:1,
      add_to_cart: "Добавить в корзину"
    },
    {
      id:3,
      product: "Разделительные-цинтрифуга",
      description: "Shimadzu UV-1900",
      key:"12hlapogb0",
      manufacturer: "Произведено: ",
      country: "Япония",
      weight: "Вес: 10 кг",
      price: "100000",
      material:"Алюминий",
      Product_category:'Анализ',
      Brands:"Labor-Microscopes",
      image:"dividing-entrifuge",
      quantity:1,
      add_to_cart: "Добавить в корзину"
    },
    {
      id:4,
      product: "Нанокристаллический микроскоп",
      description: "Z-1000 Nano",
      key:"bdlac3th91",
      manufacturer: "Произведено: ",
      country: "Швеция",
      weight: "Вес: 8 кг",
      price: "49000",
      material:"Пластик",
      Product_category:'Исследования',
      Brands:"Flottweg",
      image:"microscope",
      quantity:1,
      add_to_cart: "Добавить в корзину"
    },
    {
      id:5,
      product: "Фильтрационная-цинтрифуга",
      description: "BioGrow BG-3000",
      manufacturer: "Произведено: ",
      country: "США",
      key:"1fd95nalxu",
      weight: "Вес: 45 кг",
      price: "50000",
      material:"Сталь",
      Product_category:'Анализ',
      Brands:"Labor-Microscopes",
      image:"Filtration-cytrifuge",
      quantity:1,
      add_to_cart: "Добавить в корзину"
    },
    {
      id:6,
      product: "Ускоренная цинтрифуга",
      description: "LaserSpec LS-2000",
      manufacturer: "Произведено: ",
      country: "Китай",
      key:"wskibf58sv",
      weight: "Вес: 12 кг",
      price: "40000",
      material:"Углепластик",
      Product_category:'Исследования',
      Brands:"Rousselet Robatel",
      image:"centrifuge2",
      quantity:1,
      add_to_cart: "Добавить в корзину"
    },
    {
      id:7,
      product: "Центрифуга",
      description: "Z-1000Tech",
      manufacturer: "Произведено: ",
      country: "Германия",
      key:"bndlage5ns",
      weight: "Вес: 6 кг",
      price: "30000",
      material:"Сталь",
      Product_category:'Исследования',
      Brands:"Rousselet Robatel",
      image:"centrifuge2",
      quantity:1,
      add_to_cart: "Добавить в корзину"
    },
    {
      id:8,
      product: "Телескоп",
      description: "Bind-BD5126",
      manufacturer: "Произведено: ",
      country: "Германия",
      weight: "Вес: 43 кг",
      price: "39000",
      key:"bsflthdb83a",
      material:"Пластик",
      Product_category:'Анализ',
      Brands:"Labor-Microscopes",
      image:"telescope",
      quantity:1,
      add_to_cart: "Добавить в корзину"
    },
    {
      id:9,
      product: "Разделительные-цинтрифуга",
      description: "KandanUV-100",
      manufacturer: "Произведено: ",
      country: "Япония",
      weight: "Вес: 10 кг",
      price: "57000",
      material:"Углепластик",
      Product_category:'Исследования',
      Brands:"Flottweg",
      image:"dividing-entrifuge",
      quantity:1,
      key:"sbrg24ba9f",
      add_to_cart: "Добавить в корзину"
    }
  ];
 
  export let cart = JSON.parse(localStorage.getItem('cart')) || [];
     
    
  export function saveToStorage(updateCart) {
    cart = updateCart
    localStorage.setItem('cart', JSON.stringify(cart));
  }
  